name: headset
version: '4.2.1'
summary: Discover and collect music on YouTube
description: |
  Headset is a desktop app that turns YouTube into a world class music streaming service.
  Create collections, tune-in to a music subreddit or quickly play that song you've had stuck in your head all day!

base: core22
grade: stable
confinement: strict
compression: lzo

architectures:
  - build-on: amd64

parts:
  headset:
    plugin: dump
    source: https://headsetapp.co/headset-electron/debian/pool/non-free/h/headset/headset_${SNAPCRAFT_PROJECT_VERSION}_amd64.deb
    source-type: deb
    source-checksum: sha256/f3582c22aef8b2081ab84ea0f2933acf4e4a4e6b1b7b8f4265af5a450103c0ca
    override-pull: |
      snapcraftctl pull

      # Delete chrome-sandbox
      rm -f usr/lib/headset/chrome-sandbox

      # Fix desktop file
      sed -i 's|Exec=headset %U|Exec=headset --no-sandbox %U|g' usr/share/applications/headset.desktop
      sed -i 's|Icon=headset|Icon=usr/share/icons/hicolor/scalable/apps/headset.svg|g' usr/share/applications/headset.desktop
    stage-packages:
      - pulseaudio
      - libgtk-3-0
      - libnotify4
      - libnss3
      - libxss1
      - libxtst6
      - xdg-utils
      - libatspi2.0-0
      - libdrm2
      - libgbm1
      - libxcb-dri3-0
  cleanup:
    after:  # Make this part run last; list all your other parts here
      - headset
    plugin: nil
    build-snaps:  # List all content-snaps and base snaps you're using here
      - core22
      - gnome-42-2204
      - gtk-common-themes
    override-prime: |
      set -eux
      for snap in "core22" "gnome-42-2204" "gtk-common-themes"; do  # List all content-snaps and base snaps you're using here
        cd "/snap/$snap/current" && find . -type f,l -exec rm -f "$SNAPCRAFT_PRIME/{}" \;
      done

apps:
  headset:
    extensions: [gnome]
    command: usr/bin/headset --no-sandbox
    desktop: usr/share/applications/headset.desktop
    environment:
      TMPDIR: $XDG_RUNTIME_DIR
    plugs:
      - audio-playback
      - browser-support
      - network
      - network-bind
      - opengl
    slots:
      - headset-mpris

slots:
  headset-mpris:
    interface: mpris
    name: headset
